MeinLiX/Models/User.cs
using Microsoft.AspNetCore.Identity;

namespace MeinLiX.Models
{
    public class User : IdentityUser
    {
        public int Year { get; set; }
    }
}

MeinLiX/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using MeinLiX.Models;
using MeinLiX.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace MeinLiX.Controllers
{
    namespace CustomIdentityApp.Controllers
    {
        [Authorize(Roles = "admin")]
        public class RolesController : Controller
        {
            readonly RoleManager<IdentityRole> _roleManager;
            readonly UserManager<User> _userManager;
            public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
            {
                _roleManager = roleManager;
                _userManager = userManager;
            }
            public IActionResult Index() => View(_roleManager.Roles.ToList());

            public IActionResult Create() => View();

            [HttpPost]
            public async Task<IActionResult> Create(string name)
            {
                if (!string.IsNullOrEmpty(name))
                {
                    IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                return View(name);
            }

            [HttpPost]
            public async Task<IActionResult> Delete(string id)
            {
                IdentityRole role = await _roleManager.FindByIdAsync(id);
                if (role != null)
                {
                    _ = await _roleManager.DeleteAsync(role);
                }
                return RedirectToAction("Index");
            }

            public async Task<IActionResult> Edit(string userId)
            {
                User user = await _userManager.FindByIdAsync(userId);
                if (user != null)
                {
                    var userRoles = await _userManager.GetRolesAsync(user);
                    var allRoles = _roleManager.Roles.ToList();
                    ChangeRoleViewModel model = new ChangeRoleViewModel
                    {
                        UserId = user.Id,
                        UserEmail = user.Email,
                        UserRoles = userRoles,
                        AllRoles = allRoles
                    };
                    return View(model);
                }

                return NotFound();
            }
            [HttpPost]
            public async Task<IActionResult> Edit(string userId, List<string> roles)
            {
                User user = await _userManager.FindByIdAsync(userId);
                if (user != null)
                {
                    var userRoles = await _userManager.GetRolesAsync(user);
                   //var allRoles = _roleManager.Roles.ToList();
                    var addedRoles = roles.Except(userRoles);
                    var removedRoles = userRoles.Except(roles);
                    await _userManager.AddToRolesAsync(user, addedRoles);
                    await _userManager.RemoveFromRolesAsync(user, removedRoles);
                    return RedirectToAction("UserList");
                }

                return NotFound();
            }
        }
    }
}

MeinLiX/Controllers/UsersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using MeinLiX;
using MeinLiX.ViewModel;
using MeinLiX.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore.Migrations;

namespace MeinLiX.Controllers
{
    [Authorize(Roles = "admin")]
    public class UsersController : Controller
    {
        readonly UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (model.Year < 0 || model.Year>DateTime.Today.Year-11) {
                ModelState.AddModelError("Year","Incorrect");
            }
            if (model.Email != null)
            {
                ModelState.AddModelError("Email", "Incorrect");
            }
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email, Year = model.Year };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email, Year = user.Year };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.Year = model.Year;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                _ = await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
    }
}

MeinLiX/Views/Users/Create.cshtml
@model MeinLiX.ViewModel.CreateUserViewModel
@{
    ViewBag.Title = "User create";
}
<form asp-action="Create" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input type="text" asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="control-label"></label>
        <input type="password" asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Year" class="control-label"></label>
        <input type="number" asp-for="Year" class="form-control" />
        <span asp-validation-for="Year" class="text-danger"></span>

    </div>
    <div class="form-group">
        <input type="submit" value="Add" class="btn btn-outline-secondary" />
    </div>
</form>

MeinLiX/Views/Users/Edit.cshtml
@model MeinLiX.ViewModel.EditUserViewModel
@{
    ViewBag.Title = "User edit";
}
<form asp-action="Edit" asp-controller="Users">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input type="text" asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Year" class="control-label"></label>
        <input type="number" asp-for="Year" class="form-control" />
        <span asp-validation-for="Year" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-outline-secondary" />
    </div>
</form>

MeinLiX/Views/Users/Index.cshtml
@model IEnumerable<MeinLiX.Models.User>
@{
    ViewBag.Title = "User List";
}
<h1>User List</h1>
<a asp-action="Create">Add new user</a>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.UserName)</th>
        <th>@Html.DisplayNameFor(model => model.Year)</th>
        <th></th>
    </tr>
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Email</td>
            <td>@user.Year</td>
            <td>
                <form asp-action="Delete" asp-route-id="@user.Id" method="post">
                    <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@user.Id">Edit</a> |
                    <a class="btn btn-sm btn-primary" asp-controller="Roles" asp-action="Edit" asp-route-userid="@user.Id">EditRole</a> |
                    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                </form>
            </td>
        </tr>
    }
</table>